version: '3.7'

services:

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - gobeer-nw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - gobeer-nw

  gobber-api:
    build: .
    environment:
      GOBEER_DB_HOST: "db:5432"
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - gobeer-nw

networks:
  gobeer-nw:
