version: '3.7'

services:

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    networks:
      - gobeer-nw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - gobeer-nw

  gobber-api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      GOBEER_DB_HOST: "db:5432"
      GOBEER_TRACING_REPORTER_URI: "http://jaeger:14268/api/traces"
      GOBEER_NOTIFIER_EMAIL_URL: "http://email-api:3001"
    ports:
      - 3000:3000
    depends_on:
      - db
      - email-api
    networks:
      - gobeer-nw

  email-api:
    build: 
      context: .
      dockerfile: Dockerfile.email-api
    environment:
      EMAIL_TRACING_REPORTER_URI: "http://jaeger:14268/api/traces"
    ports:
      - 3001:3001
    networks:
      - gobeer-nw
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - gobeer-nw

networks:
  gobeer-nw:
